/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Autentica e retorna tokens */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: email */
                        email: string;
                        senha: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                401: components["responses"]["NaoAutorizado"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renova o access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokenResponse"];
                    };
                };
                401: components["responses"]["NaoAutorizado"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dados do usuário autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista usuários */
        get: {
            parameters: {
                query?: {
                    perfil?: components["schemas"]["Perfil"];
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginaUsuario"];
                    };
                };
            };
        };
        put?: never;
        /** Cria usuário */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UsuarioRequest"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                422: components["responses"]["ErroValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Detalha usuário */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                404: components["responses"]["NaoEncontrado"];
            };
        };
        /** Atualiza usuário */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UsuarioRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios/{id}/vinculos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** Define os estagiários orientados por um supervisor */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        estagiarioIds?: number[];
                    };
                };
            };
            responses: {
                /** @description Atualizado */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista pacientes visíveis ao usuário */
        get: {
            parameters: {
                query?: {
                    busca?: string;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginaPaciente"];
                    };
                };
            };
        };
        put?: never;
        /** Cadastra paciente */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PacienteRequest"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Paciente"];
                    };
                };
                422: components["responses"]["ErroValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Detalha paciente
         * @description Paciente fora do escopo do usuário responde 404, não 403: confirmar a
         *     existência de um prontuário alheio já seria vazamento de dado sensível.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Paciente"];
                    };
                };
                404: components["responses"]["NaoEncontrado"];
            };
        };
        /** Atualiza paciente */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PacienteRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Paciente"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{id}/termo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Consulta o termo de consentimento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TermoConsentimento"];
                    };
                };
                404: components["responses"]["NaoEncontrado"];
            };
        };
        /** Registra ou atualiza o termo de consentimento */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["TermoConsentimentoRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TermoConsentimento"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pacientes/{id}/evolucao": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Série histórica de peso, IMC e medidas para gráficos */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PontoEvolucao"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atendimentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista atendimentos conforme o perfil do usuário
         * @description Estagiário vê apenas os próprios. Supervisor vê os dos seus orientados.
         *     Admin vê todos.
         */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["StatusAtendimento"];
                    pacienteId?: number;
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginaAtendimento"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Abre um novo atendimento
         * @description O estagiário é sempre o usuário autenticado; o corpo não o informa.
         *     Falha com 409 `SEM_TERMO_CONSENTIMENTO` se o paciente não tiver termo
         *     LGPD com aceite, e com 422 se o supervisor informado não tiver perfil
         *     SUPERVISOR ou não orientar o estagiário.
         *     O número de prontuário é gerado pelo servidor no formato AAAA-NNNNNN,
         *     sequencial dentro do ano da data da consulta.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: int64 */
                        pacienteId: number;
                        /** Format: int64 */
                        supervisorId: number;
                        /** Format: date */
                        dataConsulta: string;
                    };
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Atendimento"];
                    };
                };
                404: components["responses"]["NaoEncontrado"];
                409: components["responses"]["Conflito"];
                422: components["responses"]["ErroValidacao"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atendimentos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /**
         * Retorna o prontuário completo
         * @description Atendimento fora do escopo do usuário responde 404, não 403 — mesma
         *     razão de /api/pacientes/{id}.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AtendimentoCompleto"];
                    };
                };
                404: components["responses"]["NaoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atendimentos/{id}/submeter": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Envia o atendimento para revisão do supervisor
         * @description Transição RASCUNHO ou DEVOLVIDO_PARA_CORRECAO → EM_REVISAO.
         *     Exclusivo do estagiário dono do atendimento.
         *
         *     Dois códigos de 409, que o frontend distingue pelo `codigo`:
         *     `TRANSICAO_INVALIDA` quando o status atual não admite a submissão, e
         *     `SECOES_INCOMPLETAS` quando falta conteúdo obrigatório — este último
         *     preenche `Erro.campos` com o caminho de cada campo pendente
         *     (`diagnostico.etiologia`, `antropometria.pesoKg`, `recordatorio`…),
         *     na ordem em que as seções aparecem no formulário.
         *
         *     São obrigatórias para submeter: queixa principal (motivo),
         *     antropometria (peso e altura), recordatório (ao menos uma refeição),
         *     diagnóstico PES (os três campos) e plano (objetivos).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Atendimento"];
                    };
                };
                403: components["responses"]["Proibido"];
                404: components["responses"]["NaoEncontrado"];
                409: components["responses"]["Conflito"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atendimentos/{id}/queixa-principal": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Salva a queixa principal */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueixaPrincipal"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["QueixaPrincipal"];
                    };
                };
                409: components["responses"]["Conflito"];
            };
        };
        trace?: never;
    };
    "/api/atendimentos/{id}/historia-clinica": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Salva a história clínica */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["HistoriaClinica"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HistoriaClinica"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/atendimentos/{id}/antropometria": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Salva a antropometria e retorna os indicadores calculados
         * @description IMC, classificação e relação cintura/quadril são calculados pelo
         *     servidor. Campos calculados enviados pelo cliente são ignorados.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AntropometriaRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Antropometria"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/atendimentos/{id}/medicamentos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** Substitui a lista de medicamentos e suplementos */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Medicamento"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Medicamento"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atendimentos/{id}/exames": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** Substitui a lista de exames bioquímicos */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ExameBioquimico"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ExameBioquimico"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atendimentos/{id}/recordatorio": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** Substitui o recordatório alimentar de 24 horas */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Refeicao"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Refeicao"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atendimentos/{id}/frequencia-alimentar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Salva a frequência alimentar e hidratação */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FrequenciaAlimentar"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FrequenciaAlimentar"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/atendimentos/{id}/comportamento-alimentar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Salva o comportamento alimentar */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ComportamentoAlimentar"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComportamentoAlimentar"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/atendimentos/{id}/diagnostico": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Salva o diagnóstico nutricional no modelo PES */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DiagnosticoPes"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DiagnosticoPes"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/atendimentos/{id}/plano": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Salva o plano de intervenção nutricional */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PlanoIntervencao"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PlanoIntervencao"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/atendimentos/{id}/metas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** Substitui a lista de metas */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Meta"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Meta"][];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/revisoes/pendentes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fila de atendimentos aguardando revisão do supervisor
         * @description Os EM_REVISAO em que o usuário autenticado é o supervisor **designado**,
         *     do mais antigo para o mais recente. Orientar o estagiário não basta:
         *     revisar é de quem foi designado no atendimento.
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginaAtendimento"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atendimentos/{id}/avaliacao": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Consulta a avaliação do atendimento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Avaliacao"];
                    };
                };
                404: components["responses"]["NaoEncontrado"];
            };
        };
        put?: never;
        /**
         * Registra a avaliação e conclui a revisão
         * @description Exige status EM_REVISAO e que o usuário seja o supervisor designado.
         *     `resultado: APROVADO` leva o atendimento a APROVADO.
         *     `resultado: DEVOLVIDO` leva a DEVOLVIDO_PARA_CORRECAO e devolve a
         *     permissão de edição ao estagiário.
         *     A nota final é calculada pelo servidor como média ponderada da rubrica.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AvaliacaoRequest"];
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Avaliacao"];
                    };
                };
                409: components["responses"]["Conflito"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/atendimentos/{id}/comentarios": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Lista comentários por seção */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComentarioSecao"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Adiciona comentário a uma seção
         * @description Escreve apenas o supervisor designado, em qualquer status: o parecer não
         *     se fecha junto com o prontuário. O estagiário dono lê, mas não escreve.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        secao: components["schemas"]["SecaoProntuario"];
                        texto: string;
                    };
                };
            };
            responses: {
                /** @description Criado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ComentarioSecao"];
                    };
                };
                403: components["responses"]["Proibido"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Erro: {
            /**
             * @description Código estável, é por ele que o cliente distingue os erros — nunca
             *     pelo texto de `mensagem`. Em uso: VALIDACAO, NAO_AUTORIZADO,
             *     SEM_PERMISSAO, NAO_ENCONTRADO, TRANSICAO_INVALIDA,
             *     SEM_TERMO_CONSENTIMENTO, SECOES_INCOMPLETAS, ERRO_INTERNO.
             * @example TRANSICAO_INVALIDA
             */
            codigo?: string;
            mensagem?: string;
            /** Format: date-time */
            timestamp?: string;
            campos?: {
                campo?: string;
                mensagem?: string;
            }[];
        };
        /** @enum {string} */
        Perfil: "ESTAGIARIO" | "SUPERVISOR" | "ADMIN";
        /** @enum {string} */
        StatusAtendimento: "RASCUNHO" | "EM_REVISAO" | "APROVADO" | "DEVOLVIDO_PARA_CORRECAO";
        /** @enum {string} */
        SecaoProntuario: "QUEIXA_PRINCIPAL" | "HISTORIA_CLINICA" | "MEDICAMENTOS" | "ANTROPOMETRIA" | "EXAMES" | "RECORDATORIO" | "FREQUENCIA_ALIMENTAR" | "COMPORTAMENTO_ALIMENTAR" | "DIAGNOSTICO" | "PLANO" | "METAS";
        /** @enum {string} */
        Frequencia: "NUNCA" | "RARAMENTE" | "SEMANAL" | "QUASE_DIARIO" | "DIARIO";
        TokenResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** @description segundos */
            expiraEm?: number;
            usuario?: components["schemas"]["Usuario"];
        };
        Usuario: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            /** Format: email */
            email?: string;
            perfil?: components["schemas"]["Perfil"];
            ativo?: boolean;
        };
        UsuarioRequest: {
            nome: string;
            /** Format: email */
            email: string;
            senha?: string;
            perfil: components["schemas"]["Perfil"];
            /** @default true */
            ativo: boolean;
        };
        Paciente: {
            /** Format: int64 */
            id?: number;
            nome?: string;
            /** Format: date */
            dataNascimento?: string;
            /** @description calculada pelo servidor */
            idade?: number;
            /** @enum {string} */
            sexo?: "FEMININO" | "MASCULINO" | "OUTRO" | "NAO_INFORMADO";
            /** @enum {string} */
            racaCor?: "BRANCA" | "PRETA" | "PARDA" | "AMARELA" | "INDIGENA" | "NAO_INFORMADO";
            telefone?: string;
            email?: string;
            possuiTermo?: boolean;
        };
        PacienteRequest: {
            nome: string;
            /** Format: date */
            dataNascimento: string;
            /** @enum {string} */
            sexo: "FEMININO" | "MASCULINO" | "OUTRO" | "NAO_INFORMADO";
            /** @enum {string} */
            racaCor?: "BRANCA" | "PRETA" | "PARDA" | "AMARELA" | "INDIGENA" | "NAO_INFORMADO";
            telefone?: string;
            /** Format: email */
            email?: string;
        };
        TermoConsentimento: {
            aceiteLgpd?: boolean;
            autorizaUsoPesquisa?: boolean;
            /** Format: date */
            dataAceite?: string;
            registradoPor?: string;
            observacoes?: string;
        };
        TermoConsentimentoRequest: {
            aceiteLgpd: boolean;
            /** @default false */
            autorizaUsoPesquisa: boolean;
            /** Format: date */
            dataAceite: string;
            observacoes?: string;
        };
        Atendimento: {
            /** Format: int64 */
            id?: number;
            numeroProntuario?: string;
            paciente?: components["schemas"]["Paciente"];
            estagiario?: components["schemas"]["Usuario"];
            supervisor?: components["schemas"]["Usuario"];
            /** Format: date */
            dataConsulta?: string;
            status?: components["schemas"]["StatusAtendimento"];
            /** @description se o usuário atual pode editar */
            editavel?: boolean;
            secoesPreenchidas?: components["schemas"]["SecaoProntuario"][];
            /** Format: date-time */
            submetidoEm?: string;
            /** Format: date-time */
            avaliadoEm?: string;
        };
        AtendimentoCompleto: components["schemas"]["Atendimento"] & {
            queixaPrincipal?: components["schemas"]["QueixaPrincipal"];
            historiaClinica?: components["schemas"]["HistoriaClinica"];
            medicamentos?: components["schemas"]["Medicamento"][];
            antropometria?: components["schemas"]["Antropometria"];
            exames?: components["schemas"]["ExameBioquimico"][];
            recordatorio?: components["schemas"]["Refeicao"][];
            frequenciaAlimentar?: components["schemas"]["FrequenciaAlimentar"];
            comportamentoAlimentar?: components["schemas"]["ComportamentoAlimentar"];
            diagnostico?: components["schemas"]["DiagnosticoPes"];
            plano?: components["schemas"]["PlanoIntervencao"];
            metas?: components["schemas"]["Meta"][];
            avaliacao?: components["schemas"]["Avaliacao"];
        };
        QueixaPrincipal: {
            motivo?: string;
            tempoQueixa?: string;
            tratamentoAnterior?: string;
            objetivoConsulta?: string;
            observacoes?: string;
        };
        HistoriaClinica: {
            doencasDiagnosticadas?: string;
            alergias?: string;
            intolerancias?: string;
            historicoFamiliar?: string;
            /** @enum {string} */
            tabagismo?: "NUNCA_FUMOU" | "EX_FUMANTE" | "FUMANTE";
            horasSono?: number;
            /** @enum {string} */
            qualidadeSono?: "RUIM" | "REGULAR" | "BOA";
            /** @enum {string} */
            nivelEstresse?: "BAIXO" | "MODERADO" | "ALTO";
            /** @enum {string} */
            habitoIntestinal?: "DIARIO" | "ALTERNADO" | "CONSTIPADO" | "DIARREICO" | "IRREGULAR";
            praticaAtividadeFisica?: boolean;
            descricaoAtividade?: string;
            observacoes?: string;
        };
        Medicamento: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            tipo: "MEDICAMENTO" | "SUPLEMENTO";
            nome: string;
            dose?: string;
            frequencia?: string;
        };
        AntropometriaRequest: {
            pesoKg?: number;
            alturaCm?: number;
            circCinturaCm?: number;
            circQuadrilCm?: number;
            percentualGordura?: number;
            massaMagraKg?: number;
            /** Format: date */
            aferidoEm?: string;
        };
        Antropometria: components["schemas"]["AntropometriaRequest"] & {
            readonly imc?: number;
            readonly classificacaoImc?: string;
            readonly relacaoCinturaQuadril?: number;
            /** @enum {string} */
            readonly riscoCardiovascular?: "BAIXO" | "AUMENTADO" | "MUITO_AUMENTADO";
            readonly rcqElevada?: boolean;
        };
        ExameBioquimico: {
            /** Format: int64 */
            id?: number;
            nomeExame: string;
            valor?: number;
            unidade?: string;
            /** Format: date */
            dataExame?: string;
            valorReferencia?: string;
        };
        Refeicao: {
            /** Format: int64 */
            id?: number;
            /** @enum {string} */
            tipoRefeicao: "DESJEJUM" | "LANCHE_MANHA" | "ALMOCO" | "LANCHE_TARDE" | "JANTAR" | "CEIA" | "OUTRO";
            /** @example 07:30 */
            horario?: string;
            localRefeicao?: string;
            ordem?: number;
            itens?: {
                /** Format: int64 */
                id?: number;
                alimento: string;
                quantidade?: string;
                medidaCaseira?: string;
                ordem?: number;
            }[];
        };
        FrequenciaAlimentar: {
            frutas?: components["schemas"]["Frequencia"];
            verdurasLegumes?: components["schemas"]["Frequencia"];
            ultraprocessados?: components["schemas"]["Frequencia"];
            refrigerante?: components["schemas"]["Frequencia"];
            bebidaAlcoolica?: components["schemas"]["Frequencia"];
            cafe?: components["schemas"]["Frequencia"];
            aguaMlDia?: number;
            observacoes?: string;
        };
        ComportamentoAlimentar: {
            comeAssistindoTela?: boolean;
            comeRapido?: boolean;
            pulaRefeicoes?: boolean;
            compulsaoAlimentar?: boolean;
            alimentacaoEmocional?: boolean;
            restricaoAlimentar?: boolean;
            observacoes?: string;
        };
        DiagnosticoPes: {
            problema?: string;
            etiologia?: string;
            sinaisSintomas?: string;
        };
        PlanoIntervencao: {
            objetivos?: string;
            prescricaoEnergeticaKcal?: number;
            percCarboidrato?: number;
            percProteina?: number;
            percLipideo?: number;
            estrategiasComportamentais?: string;
            educacaoAlimentar?: string;
        };
        Meta: {
            /** Format: int64 */
            id?: number;
            descricao: string;
            /** @enum {string} */
            prazo: "CURTO" | "MEDIO";
            indicador?: string;
            /** Format: date */
            dataRetorno?: string;
        };
        AvaliacaoRequest: {
            /** @enum {string} */
            resultado: "APROVADO" | "DEVOLVIDO";
            parecerGeral?: string;
            itens: {
                criterio: string;
                /** @default 1 */
                peso: number;
                nota: number;
                comentario?: string;
            }[];
        };
        Avaliacao: {
            /** Format: int64 */
            id?: number;
            supervisor?: components["schemas"]["Usuario"];
            readonly notaFinal?: number;
            /** @enum {string} */
            resultado?: "APROVADO" | "DEVOLVIDO";
            parecerGeral?: string;
            /** Format: date-time */
            avaliadoEm?: string;
            itens?: {
                /** Format: int64 */
                id?: number;
                criterio?: string;
                peso?: number;
                nota?: number;
                comentario?: string;
            }[];
        };
        ComentarioSecao: {
            /** Format: int64 */
            id?: number;
            autor?: components["schemas"]["Usuario"];
            secao?: components["schemas"]["SecaoProntuario"];
            texto?: string;
            resolvido?: boolean;
            /** Format: date-time */
            criadoEm?: string;
        };
        PontoEvolucao: {
            /** Format: date */
            dataConsulta?: string;
            pesoKg?: number;
            imc?: number;
            circCinturaCm?: number;
            circQuadrilCm?: number;
        };
        PaginaUsuario: components["schemas"]["Pagina"] & {
            content?: components["schemas"]["Usuario"][];
        };
        PaginaPaciente: components["schemas"]["Pagina"] & {
            content?: components["schemas"]["Paciente"][];
        };
        PaginaAtendimento: components["schemas"]["Pagina"] & {
            content?: components["schemas"]["Atendimento"][];
        };
        Pagina: {
            totalElements?: number;
            totalPages?: number;
            number?: number;
            size?: number;
        };
    };
    responses: {
        /** @description Credenciais ausentes ou inválidas */
        NaoAutorizado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
        /** @description Sem permissão para este recurso */
        Proibido: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
        /** @description Recurso não encontrado */
        NaoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
        /** @description Operação inválida no estado atual */
        Conflito: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
        /** @description Falha de validação */
        ErroValidacao: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
    };
    parameters: {
        Id: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
