-- =============================================================
-- NutriClinica — V2 (vazia por decisão de segurança)
--
-- Esta migration criava três usuários de demonstração com a senha "senha123",
-- hash publicado neste repositório. Migration não distingue ambiente: o mesmo
-- arquivo que semeia a base local roda no primeiro deploy, e essas contas
-- entrariam em produção junto com o schema.
--
-- Para onde foi cada coisa:
--   * usuários de demonstração  -> SeedDesenvolvimentoRunner (@Profile dev, it)
--   * administrador de produção -> AdminInicialRunner (@Profile prod), que lê
--     ADMIN_EMAIL e ADMIN_PASSWORD e só age com a tabela usuario vazia.
--
-- O arquivo continua existindo, e vazio, porque a versão 2 já consta do
-- flyway_schema_history de bases criadas antes desta mudança. Apagá-lo faria o
-- Flyway recusar a partida por migration aplicada e não resolvida.
--
-- Bases que aplicaram a versão anterior acusam divergência de checksum. Em
-- desenvolvimento, o caminho é recriar o volume:
--     docker compose down -v && docker compose up -d
-- Preservando os dados, `flyway repair` reescreve o checksum registrado.
-- =============================================================
